# Generated by Django 4.2.1 on 2023-05-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("firstName", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("fixTel", models.CharField(blank=True, max_length=255, null=True)),
                ("whatApp", models.CharField(blank=True, max_length=255, null=True)),
                ("otherCanal", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True, default="", max_length=255, upload_to=""
                    ),
                ),
                ("linkedin", models.URLField(blank=True, max_length=255, null=True)),
                ("instagram", models.URLField(blank=True, max_length=255, null=True)),
                ("facebook", models.URLField(blank=True, max_length=255, null=True)),
                ("github", models.URLField(blank=True, max_length=255, null=True)),
                ("gitlab", models.URLField(blank=True, max_length=255, null=True)),
                ("bitbucket", models.URLField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "video",
                    models.FileField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                ("tjm", models.CharField(blank=True, max_length=255, null=True)),
                ("annotations", models.TextField(blank=True)),
                ("availability", models.CharField(blank=True, max_length=255)),
                ("modeReglement", models.CharField(blank=True, max_length=255)),
                ("bankAccount", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer",
                        to="core.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeveloperSkill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="core.developer",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="core.level",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="developer",
            name="skills",
            field=models.ManyToManyField(
                related_name="developers",
                through="core.DeveloperSkill",
                to="core.skill",
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developers",
                to="core.status",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.country"
            ),
        ),
    ]
