# Generated by Django 4.2.1 on 2023-05-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("firstname", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("whatApps", models.CharField(max_length=100, null=True)),
                ("age", models.IntegerField()),
                ("address", models.TextField(max_length=400)),
                ("country", models.CharField(max_length=150)),
                ("mail", models.EmailField(max_length=254)),
                ("github", models.CharField(max_length=130)),
                ("linkedin", models.CharField(max_length=140)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        help_text="Photo de profile",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True, help_text="CV en pdf", null=True, upload_to=""
                    ),
                ),
                ("site", models.CharField(blank=True, max_length=140, null=True)),
                ("page", models.CharField(max_length=140)),
                (
                    "kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.kind",
                    ),
                ),
                ("languages", models.ManyToManyField(blank=True, to="core.languages")),
            ],
        ),
    ]
