# Generated by Django 4.2.1 on 2023-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_developerskill_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="updated_at",
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
