# Generated by Django 4.2.1 on 2023-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_developer_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="developer",
            old_name="whatApp",
            new_name="whatsApp",
        ),
        migrations.AddField(
            model_name="developer",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("maculin", "maculin"), ("feminin", "feminin")],
                default="maculin",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="developerskill",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
