# Generated by Django 4.2.1 on 2023-05-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0001_initial"),
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "updated_at",
                    models.DateTimeField(auto_created=True, auto_now=True, null=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Nom du développeur", max_length=255
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        blank=True, help_text="Prénom du développeur", max_length=255
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Téléphone du développeur", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email du développeur", max_length=255
                    ),
                ),
                (
                    "fixTel",
                    models.CharField(
                        blank=True,
                        help_text="Téléphone fixe du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "whatsApp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "otherCanal",
                    models.CharField(
                        blank=True,
                        help_text="Autre canal du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        help_text="Instagram du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        help_text="Facebook du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True,
                        help_text="GitHub du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gitlab",
                    models.URLField(
                        blank=True,
                        help_text="GitLab du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bitbucket",
                    models.URLField(
                        blank=True,
                        help_text="BitBucket du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Site web du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tjm",
                    models.IntegerField(
                        blank=True, help_text="TJM du développeur", null=True
                    ),
                ),
                (
                    "annotations",
                    models.TextField(
                        blank=True, help_text="Annotations du développeur"
                    ),
                ),
                (
                    "availability",
                    models.TextField(
                        blank=True, help_text="Disponibilité du développeur"
                    ),
                ),
                (
                    "modeReglement",
                    models.CharField(
                        blank=True,
                        help_text="Mode de règlement du développeur",
                        max_length=255,
                    ),
                ),
                (
                    "bankAccount",
                    models.CharField(
                        blank=True,
                        help_text="Compte bancaire du développeur",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        default="",
                        help_text="CV du développeur",
                        max_length=255,
                        upload_to="cv/",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="",
                        help_text="Photo du développeur",
                        max_length=255,
                        upload_to="photos/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        default="",
                        help_text="Video du développeur",
                        max_length=255,
                        null=True,
                        upload_to="videos/",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("maculin", "maculin"), ("feminin", "feminin")],
                        default="maculin",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer",
                        to="address.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Developpeur",
                "verbose_name_plural": "Developpeurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Langue",
                "verbose_name_plural": "Langues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperSkill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("experience", models.IntegerField(blank=True, null=True)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="developer.developer",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="developer.level",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="skill.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competence du developpeur",
                "verbose_name_plural": "Competences des developpeurs",
            },
        ),
        migrations.AddField(
            model_name="developer",
            name="languages",
            field=models.ManyToManyField(
                related_name="developer", to="developer.language"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="skills",
            field=models.ManyToManyField(
                related_name="developer",
                through="developer.DeveloperSkill",
                to="skill.skill",
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developers",
                to="developer.status",
            ),
        ),
    ]
