# Generated by Django 4.2.1 on 2023-05-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0001_initial"),
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now=True,
                        null=True,
                        verbose_name="Date de modification",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Nom du développeur",
                        max_length=255,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        help_text="Prénom du développeur",
                        max_length=255,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Téléphone du développeur",
                        max_length=255,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email du développeur",
                        max_length=255,
                        verbose_name="Email",
                    ),
                ),
                (
                    "fixTel",
                    models.CharField(
                        blank=True,
                        help_text="Téléphone fixe du développeur",
                        max_length=255,
                        null=True,
                        verbose_name="Téléphone fixe",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Adresse du développeur",
                        max_length=255,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        help_text="CV du développeur",
                        max_length=255,
                        upload_to="developers/cv/%Y/%m/%d/",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Photo du développeur",
                        max_length=255,
                        upload_to="developers/photos/%Y/%m/%d/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Video du développeur",
                        max_length=255,
                        null=True,
                        upload_to="developers/videos/%Y/%m/%d/",
                    ),
                ),
                (
                    "whatsApp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp du développeur",
                        max_length=255,
                        null=True,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "otherCanal",
                    models.CharField(
                        blank=True,
                        help_text="Autre canal du développeur",
                        max_length=255,
                        null=True,
                        verbose_name="Autre canal",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn du développeur",
                        max_length=255,
                        null=True,
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        help_text="Instagram du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        help_text="Facebook du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True,
                        help_text="GitHub du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gitlab",
                    models.URLField(
                        blank=True,
                        help_text="GitLab du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bitbucket",
                    models.URLField(
                        blank=True,
                        help_text="BitBucket du développeur",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Site web du développeur",
                        max_length=255,
                        null=True,
                        verbose_name="Site web",
                    ),
                ),
                (
                    "tjm",
                    models.IntegerField(
                        blank=True, help_text="TJM du développeur", null=True
                    ),
                ),
                (
                    "annotations",
                    models.TextField(
                        blank=True, help_text="Annotations du développeur"
                    ),
                ),
                (
                    "availability",
                    models.TextField(
                        blank=True,
                        help_text="Disponibilité du développeur",
                        verbose_name="Disponibilité",
                    ),
                ),
                (
                    "modeReglement",
                    models.CharField(
                        blank=True,
                        help_text="Mode de règlement du développeur",
                        max_length=255,
                        verbose_name="Mode de règlement",
                    ),
                ),
                (
                    "bankAccount",
                    models.CharField(
                        blank=True,
                        help_text="Compte bancaire du développeur",
                        max_length=255,
                        verbose_name="Compte bancaire",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("maculin", "maculin"), ("feminin", "feminin")],
                        default="maculin",
                        max_length=255,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developers",
                        related_query_name="developer",
                        to="address.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Developpeur",
                "verbose_name_plural": "Developpeurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="langue"
                    ),
                ),
                ("code", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Langue",
                "verbose_name_plural": "Langues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="niveau",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="ordre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="statut",
                    ),
                ),
                (
                    "isDefault",
                    models.BooleanField(default=False, verbose_name="par défaut"),
                ),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperSkill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "experience",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Experience"
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="developer.developer",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="developer.level",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_skills",
                        to="skill.skill",
                        verbose_name="Competence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competence du developpeur",
                "verbose_name_plural": "Competences du developpeur",
            },
        ),
        migrations.AddField(
            model_name="developer",
            name="languages",
            field=models.ManyToManyField(
                related_name="developer", to="developer.language"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="skills",
            field=models.ManyToManyField(
                related_name="developer",
                through="developer.DeveloperSkill",
                to="skill.skill",
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developers",
                to="developer.status",
            ),
        ),
    ]
