# Generated by Django 4.2.1 on 2023-05-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("developer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ["order"],
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
            },
        ),
        migrations.RemoveField(
            model_name="level",
            name="value",
        ),
        migrations.RemoveField(
            model_name="status",
            name="code",
        ),
        migrations.AddField(
            model_name="level",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="isDefault",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="developer",
            name="annotations",
            field=models.TextField(help_text="Annotations du développeur"),
        ),
        migrations.AlterField(
            model_name="developer",
            name="availability",
            field=models.TextField(help_text="Disponibilité du développeur"),
        ),
        migrations.AlterField(
            model_name="developer",
            name="bankAccount",
            field=models.CharField(
                help_text="Compte bancaire du développeur", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="bitbucket",
            field=models.URLField(
                help_text="BitBucket du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="cv",
            field=models.FileField(
                default="",
                help_text="CV du développeur",
                max_length=255,
                upload_to="cv/",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="email",
            field=models.EmailField(help_text="Email du développeur", max_length=255),
        ),
        migrations.AlterField(
            model_name="developer",
            name="facebook",
            field=models.URLField(
                help_text="Facebook du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="firstName",
            field=models.CharField(help_text="Prénom du développeur", max_length=255),
        ),
        migrations.AlterField(
            model_name="developer",
            name="fixTel",
            field=models.CharField(
                help_text="Téléphone fixe du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="github",
            field=models.URLField(
                help_text="GitHub du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="gitlab",
            field=models.URLField(
                help_text="GitLab du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="instagram",
            field=models.URLField(
                help_text="Instagram du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="linkedin",
            field=models.URLField(
                help_text="LinkedIn du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="modeReglement",
            field=models.CharField(
                help_text="Mode de règlement du développeur", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="name",
            field=models.CharField(help_text="Nom du développeur", max_length=255),
        ),
        migrations.AlterField(
            model_name="developer",
            name="otherCanal",
            field=models.CharField(
                help_text="Autre canal du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="phone",
            field=models.CharField(
                help_text="Téléphone du développeur", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="photo",
            field=models.ImageField(
                default="",
                help_text="Photo du développeur",
                max_length=255,
                upload_to="photos/",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="sex",
            field=models.CharField(
                choices=[("maculin", "maculin"), ("feminin", "feminin")],
                default="maculin",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developers",
                to="developer.status",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="tjm",
            field=models.IntegerField(help_text="TJM du développeur", null=True),
        ),
        migrations.AlterField(
            model_name="developer",
            name="video",
            field=models.FileField(
                default="",
                help_text="Video du développeur",
                max_length=255,
                null=True,
                upload_to="videos/",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="website",
            field=models.URLField(
                help_text="Site web du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="whatsApp",
            field=models.CharField(
                help_text="WhatsApp du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developerskill",
            name="experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
