# Generated by Django 4.2.1 on 2023-05-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="bitbucket",
            field=models.URLField(
                blank=True,
                help_text="BitBucket du développeur",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="cv",
            field=models.FileField(
                help_text="CV du développeur",
                max_length=255,
                upload_to="developers/cvs/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="email",
            field=models.EmailField(
                help_text="Email du développeur",
                max_length=255,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="github",
            field=models.URLField(
                blank=True,
                help_text="GitHub du développeur",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="gitlab",
            field=models.URLField(
                blank=True,
                help_text="GitLab du développeur",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="instagram",
            field=models.URLField(
                blank=True,
                help_text="Instagram du développeur",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="linkedin",
            field=models.URLField(
                blank=True,
                help_text="LinkedIn du développeur",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="LinkedIn",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Site web du développeur",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Site web",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="whatsApp",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp du développeur",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="WhatsApp",
            ),
        ),
    ]
