# Generated by Django 4.2.1 on 2023-05-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("developer", "0002_alter_developer_bitbucket_alter_developer_cv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("description", models.TextField(verbose_name="description")),
                ("startDate", models.DateField(verbose_name="date de début")),
                (
                    "endDate",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                (
                    "isCurrent",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="cocher si c'est l'expérience actuelle",
                        null=True,
                        verbose_name="actuel",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="adresse")),
                (
                    "enterprise",
                    models.CharField(max_length=255, verbose_name="entreprise"),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="developer.developer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expérience",
                "verbose_name_plural": "Expériences",
                "ordering": ["startDate"],
            },
        ),
    ]
