# Generated by Django 4.2.1 on 2023-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developer", "0002_alter_level_options_remove_level_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="developerskill",
            options={
                "verbose_name": "Competence du developpeur",
                "verbose_name_plural": "Competences du developpeur",
            },
        ),
        migrations.AlterField(
            model_name="developer",
            name="availability",
            field=models.TextField(
                help_text="Disponibilité du développeur", verbose_name="Disponibilité"
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="bitbucket",
            field=models.URLField(
                blank=True,
                help_text="BitBucket du développeur",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="email",
            field=models.EmailField(
                help_text="Email du développeur", max_length=255, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="facebook",
            field=models.URLField(
                blank=True,
                help_text="Facebook du développeur",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="firstName",
            field=models.CharField(
                help_text="Prénom du développeur", max_length=255, verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="fixTel",
            field=models.CharField(
                blank=True,
                help_text="Téléphone fixe du développeur",
                max_length=255,
                null=True,
                verbose_name="Téléphone fixe",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="github",
            field=models.URLField(
                blank=True, help_text="GitHub du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="gitlab",
            field=models.URLField(
                blank=True, help_text="GitLab du développeur", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="instagram",
            field=models.URLField(
                blank=True,
                help_text="Instagram du développeur",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="linkedin",
            field=models.URLField(
                blank=True,
                help_text="LinkedIn du développeur",
                max_length=255,
                null=True,
                verbose_name="LinkedIn",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="name",
            field=models.CharField(
                help_text="Nom du développeur", max_length=255, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="otherCanal",
            field=models.CharField(
                blank=True,
                help_text="Autre canal du développeur",
                max_length=255,
                null=True,
                verbose_name="Autre canal",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="phone",
            field=models.CharField(
                help_text="Téléphone du développeur",
                max_length=255,
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="sex",
            field=models.CharField(
                choices=[("maculin", "maculin"), ("feminin", "feminin")],
                default="maculin",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="tjm",
            field=models.IntegerField(
                blank=True, help_text="TJM du développeur", null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="video",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Video du développeur",
                max_length=255,
                null=True,
                upload_to="videos/",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Site web du développeur",
                max_length=255,
                null=True,
                verbose_name="Site web",
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="whatsApp",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp du développeur",
                max_length=255,
                null=True,
                verbose_name="WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="langue"),
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="niveau",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="order",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="ordre"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="isDefault",
            field=models.BooleanField(default=False, verbose_name="par défaut"),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="statut",
            ),
        ),
    ]
