# Generated by Django 4.2.1 on 2023-05-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formation",
            name="projects",
        ),
    ]
