# Generated by Django 4.2.1 on 2023-05-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="pays"),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Adresse")),
                ("city", models.CharField(max_length=255, verbose_name="Ville")),
                ("street", models.CharField(max_length=255, verbose_name="Rue")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        related_query_name="address",
                        to="address.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "ordering": ["country"],
            },
        ),
    ]
