# Generated by Django 4.2.1 on 2023-05-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="pays"),
                ),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["name"],
            },
        ),
    ]
