# Generated by Django 4.2.1 on 2023-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="compétence"
            ),
        ),
        migrations.AlterField(
            model_name="skillcategory",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Categorie de competence",
            ),
        ),
    ]
